### ISSUE TITLE
Id or annotation issue in gene selection post DGE

### ISSUE THREAD

**Issue by Hoohm** [federicomarini/ideal#2]
Hello @federicomarini 

Here is the problem I get when using the gene selected from the left menu.

This is the table from below and you can see that the Id column seems fine but that the table also has rownames (I guess).

![image](https://user-images.githubusercontent.com/1267560/56288433-15da0180-611f-11e9-8df5-d5b344cb6708.png)

On the left menu, I get this: 
![image](https://user-images.githubusercontent.com/1267560/56288532-45890980-611f-11e9-9f31-8ebf5aa876b5.png)

My guess is that the selection is based on the rownames of the table instead of the id column.

I'm trying to look for the bug myself but I'm having a hard time navigating the code since I'm not that used to shiny app code.

I think I'm trying to find where ths variable is instantiated: https://github.com/federicomarini/ideal/blob/f9931316eab54e4fa8ee385da0bc31a4752a7d66/R/ideal.R#L2875

EDIT: for context, I use gene_symbol as my main ID. I guess you use Ensembl ID by default and that is where this is problematic.

**Comment by Hoohm** [comment]
Adding also that in the functional analysis tab and try to run a GO analysis, I get this warning:
`Warning: Error in .testForValidKeys: 'keys' must be a character vector`
I guess this stems from the same issue. Something linked to the ID used.

**Comment by Hoohm** [comment]
Update: if you don't load the annotation data, this does not occur. Hope this helps

**Comment by federicomarini** [comment]
Hi Patrick.
You are right in guessing it is something with the annotation format.

Indeed the format has to follow these rules:
- see https://github.com/federicomarini/ideal/blob/master/inst/extdata/datainput.md
- a screenshot for that can be found in `pcaExplorer`'s documentation - link here: https://github.com/federicomarini/pcaExplorer/blob/master/inst/www/help_dataformats.png

In summary: just edit slightly the annotation format and it should work

**Comment by Hoohm** [comment]
So my next question is, would you enforce ensembl IDs as the main ID used in the count matrix? I'm ok with making the change in our pipeline.

**Comment by federicomarini** [comment]
I'd strongly recommend it because of the uniqueness feature that they kind of guarantee + stability across released versions

**Comment by Hoohm** [comment]
@federicomarini Tried with having ensembl IDs as the main ID in my counts and now the bug is gone.

Would be wise to "force" users to use ensembl ids by checking if the count columns actually match ensembl ids, fix the bug if the users choose otherwise or make some tools unavailable if using something other than ensembl ids?

**Comment by federicomarini** [comment]
I have been thinking of enforcing this, but it could cut out some users, or also situations where the dataset cannot have these type of identifiers.
Therefore I opted for a more liberal "high recommendation" 😄 

Glad you fixed the issue, anyway!
F
